### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by sandeepshiven** [securas/SealedBite#2]
I am a linux beginner and I can't find any installation guide on the website.
How can I install/play this game on ubuntu 18.04 ?

**Comment by asheraryam** [comment]
The binaries are already on the itch page so you can download them and run as executable directly.
https://securas.itch.io/sealedbite

If you want to run this source project, download the godot engine (~25mb) and import this project. https://godotengine.org/download/windows

**Comment by securas** [comment]
Thanks @asheraryam for the quick and complete response!

**Comment by sandeepshiven** [comment]
> The binaries are already on the itch page so you can download them and run as executable directly.
> https://securas.itch.io/sealedbite
> 
> If you want to run this source project, download the godot engine (~25mb) and import this project. https://godotengine.org/download/windows

I have downloaded the zip file for linux and after extracting tried to run the binary file but it is not working.

**Comment by securas** [comment]
you probably need to change the binary permissions to executable

**Comment by sandeepshiven** [comment]
how to do that??

**Comment by securas** [comment]
that's a linux thing... I really have no idea but probably something to do with the command
chmod a+x executable_filename
google is your friend

**Comment by sandeepshiven** [comment]
yeah i have found it in google and game works now
thanks
