### ISSUE TITLE
stuck at the godot logo and i just hear audio 

### ISSUE THREAD

**Issue by muafakul** [securas/SealedBite#6]
E 0:00:06.489   open_and_parse: The MD5 sum of the decrypted file does not match the expected value. It could be that the file is corrupt, or that the provided decryption key is invalid.
  <C++ Error>   Condition "String::md5(hash) != String::md5(md5d)" is true. Returned: ERR_FILE_CORRUPT
  <C++ Source>  core/io/file_access_encrypted.cpp:97 @ open_and_parse()
  <Stack Trace> gamestate.gd:98 @ _load_gamestate()
                gamestate.gd:108 @ check_gamestate_file()
                start_menu.gd:10 @ _ready()
                main.gd:57 @ load_screen()
                main.gd:115 @ _on_screentimer_timeout()

**Comment by securas** [comment]
Try deleting the gamestate file

**Comment by muafakul** [comment]
i did it 
![image](https://user-images.githubusercontent.com/13078369/76435582-c1e8a300-63e9-11ea-91e0-fe374e59fc97.png)

**Comment by muafakul** [comment]
i restored it then now it works ,i dont know why

**Comment by muafakul** [comment]
but when i press j or x ,, nothing happened

**Comment by securas** [comment]
I didn't the gamestate.gd file. I meant the savegame file
