### ISSUE TITLE
Player goes through water and can't jump out of it

### ISSUE THREAD

**Issue by hiulit** [securas/SealedBite#7]
Godot 3.2.stable.official
MacOS Mojave

![sealed-bite-water-issue](https://user-images.githubusercontent.com/481475/77156167-1998a580-6a9f-11ea-862e-4f458f09c298.gif)

**Comment by securas** [comment]
This game is only for Godot 3.1.2. It is not compatible with Godot 3.2

**Comment by hiulit** [comment]
Yes, you are right. I run it with 3.1.2 and the player dies.

**Comment by securas** [comment]
I updated the title to try to make it clear... Thanks for reporting

**Comment by erasin** [comment]
compatible with Godot 3.2 @hiulit 
props/water/water.gd 

	$player_death/collision.disabled = false

**Comment by securas** [comment]
Try using 3.1. The game is not compatible with 3.2.
